### ISSUE TITLE
Export error on nextjs.

### ISSUE THREAD

**Issue by jrcity** [OsamaHIma/translate-easy#1]
I encountering this error after installing the package on my nextjs project

```error /home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36) {
  digest: undefined
}
```

**Comment by OsamaHIma** [comment]
Hi Jrcity, 

Thank you for reaching out about the error you encountered. In order to better understand the issue and provide you with a solution, could you please provide more information about the error? 

It would be helpful if you could provide a screenshot of the error message and any relevant code snippets, such as how you are importing the `Translate` component and how you are wrapping your app with the `LanguageProvider`. Additionally, please let us know if you are using the `"use client"` statement at the top of every file where you are importing any components from the package.

With this additional information, we can better diagnose the issue and provide a solution. Thank you for your cooperation and we look forward to hearing back from you soon.

**Comment by jrcity** [comment]
Okay Here is how to reproduce the error on nextjs 

## setup next-app `npx create-next-app my-app`
note: I'm using typescript here and also using the do

## install the package `npm install translate-easy`

## root file `_app.tsx`
```
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { LanguageProvider } from "translate-easy";

"use client"

export default function App({ Component, pageProps }: AppProps) {
	return (
	<LanguageProvider
			languages={[
				{ code: "ar", name: "Arabic" },
				{ code: "en", name: "English" },
				{ code: "fr", name: "French" },
				{ code: "es", name: "Spanish" },
				{ code: "de", name: "German" },
				{ code: "it", name: "Italian" },
				{ code: "ja", name: "Japanese" },
				{ code: "ko", name: "Korean" },
				{ code: "zh-CN", name: "Chinese Simplified" },
				{ code: "zh-TW", name: "Chinese Traditional" },
			]}
		>
			<Component {...pageProps} />
		</LanguageProvider>
	);
}
```

## `// LocalePicker.tsx` file
```
"use client"
import { LanguageSelector } from 'translate-easy';
export function LocalePicker() {
	return  <LanguageSelector />
}

```

this is the complete full error code
``` error /home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36) {
  digest: undefined
}
/home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36)
/home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36)
- warn Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
- error /home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36) {
  digest: undefined
}
/home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36)

```

**Comment by OsamaHIma** [comment]
Hello,

I noticed that you are using the `pages` directory instead of the recommended `app` directory for your Next.js project. Please note that the package has not been tested using the `pages` directory, and that may be one of the reasons you are experiencing issues.

Additionally, there are some adjustments that you may need to consider in your code. Firstly, the `use client` directive MUST be on the top level, as specified in the [Next.js documentation](https://nextjs.org/docs/getting-started/react-essentials#client-components). Secondly, it is unnecessary to specify the default languages in the `LanguageProvider` component.

Here is an updated version of your code with these adjustments:

``` jsx 
"use client";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { LanguageProvider } from "translate-easy";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <LanguageProvider>
      <Component {...pageProps} />
    </LanguageProvider>
  );
}
```

Finally, please ensure that you have installed the latest version of the package, which is currently 1.2.2, to ensure that you are using the most up-to-date features and bug fixes.

I hope this helps. Let me know if you have any further questions.

**Comment by jrcity** [comment]
> Hello,
> 
> I noticed that you are using the `pages` directory instead of the recommended `app` directory for your Next.js project. Please note that the package has not been tested using the `pages` directory, and that may be one of the reasons you are experiencing issues.
> 
> Additionally, there are some adjustments that you may need to consider in your code. Firstly, the `use client` directive MUST be on the top level, as specified in the [Next.js documentation](https://nextjs.org/docs/getting-started/react-essentials#client-components). Secondly, it is unnecessary to specify the default languages in the `LanguageProvider` component.
> 
> Here is an updated version of your code with these adjustments:
> 
> ```js
> "use client";
> import "@/styles/globals.css";
> import type { AppProps } from "next/app";
> import { LanguageProvider } from "translate-easy";
> 
> export default function App({ Component, pageProps }: AppProps) {
>   return (
>     <LanguageProvider>
>       <Component {...pageProps} />
>     </LanguageProvider>
>   );
> }
> ```
> 
> Finally, please ensure that you have installed the latest version of the package, which is currently 1.2.2, to ensure that you are using the most up-to-date features and bug fixes.
> 
> I hope this helps. Let me know if you have any further questions.

I made use to this snippets and I am still getting the same errors.

```
/home/jr/projects/afruna-ecommerce/vendor/node_modules/translate-easy/dist/index.js:1
export { useLanguage, LanguageProvider } from "./LanguageContext";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at translate-easy (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:87:18)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/_app.tsx:9:72)
    at ./src/pages/_app.tsx (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:33:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=!:5:80)
    at ./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F_app&absolutePagePath=private-next-pages%2F_app&preferredRegion=! (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:97:39)
    at /home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:98:28
    at Object.<anonymous> (/home/jr/projects/afruna-ecommerce/vendor/.next/server/pages/_app.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/require.js:156:12)
    at /home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:65:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async loadComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/load-components.js:63:33)
    at async DevServer.findPageComponentsImpl (/home/jr/projects/afruna-ecommerce/vendor/node_modules/next/dist/server/next-server.js:762:36)

```
